export const LOAD_WEATHERS_REQUESTED = "WEATHER/LOAD_WEATHERS_REQUESTED"
export const LOAD_WEATHERS_FULFILLED = "WEATHER/LOAD_WEATHERS_FULFILLED"
export const LOAD_WEATHERS_REJECTED = "WEATHER/LOAD_WEATHERS_REJECTED";
